
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Student
 */
public class myQueue extends javax.swing.JFrame {

    /**
     * Creates new form myQueue
     */
    int [] qAry = new int [5];
    int front = 0;
    int rear = 0;
    int i =0;
    int z =0;
    
    public myQueue() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Enqueue = new javax.swing.JButton();
        Dequeue = new javax.swing.JButton();
        Print = new javax.swing.JButton();
        Exit = new javax.swing.JButton();
        Move = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Enqueue.setText("Enqueue");
        Enqueue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnqueueActionPerformed(evt);
            }
        });

        Dequeue.setText("Dequeue");
        Dequeue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DequeueActionPerformed(evt);
            }
        });

        Print.setText("Print");
        Print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrintActionPerformed(evt);
            }
        });

        Exit.setText("Exit");
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });

        Move.setText("Move");
        Move.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MoveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(168, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Dequeue)
                    .addComponent(Enqueue)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Move)
                            .addComponent(Exit)
                            .addComponent(Print))))
                .addGap(157, 157, 157))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(Enqueue)
                .addGap(32, 32, 32)
                .addComponent(Dequeue)
                .addGap(32, 32, 32)
                .addComponent(Print)
                .addGap(33, 33, 33)
                .addComponent(Exit)
                .addGap(18, 18, 18)
                .addComponent(Move)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_ExitActionPerformed

    private void DequeueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DequeueActionPerformed
        // TODO add your handling code here:
            for(front=0;front<qAry.lengt;front++) {
                if(qAry[front]>0) {
                    this.qAry[front] = 0;
                    JOptionPane.showMessagedialog(null,"Dequeued");
                    break;
                }
            }
    }//GEN-LAST:event_DequeueActionPerformed

    private void PrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrintActionPerformed
        // TODO add your handling code here:
        String value = "Queue Elements:\n";
        for(int i = 0;i< qAry.length;i++) {
            if (i== qAry.length-1){
                value += qAry[qAry.length-1];;
                JOptionPane.showMessageDialog(null, value);
                break;
            }
            value += qAry[i] + ", ";
        }
    }//GEN-LAST:event_PrintActionPerformed

    private void EnqueueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnqueueActionPerformed
        // TODO add your handling code here:
        if (i!= qAry.length){
            int n = Integer.parseInt(JOptionPane.showInputDialog("Enquee:"));
            this.qAry[rear]=n;
            rear++;
            i++;
        }else{
            JOptionPane.showMessageDialog(null,"Full!");
        }
    }//GEN-LAST:event_EnqueueActionPerformed

    private void MoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MoveActionPerformed
        // TODO add your handling code here:
        for (int i=0; i<qAry.length;i++){
            if (qAry[i]==0){
                qAry[i]=Integer.parseInt(JOptionPane.showInputDialog("Reenquee:"));
                break;
            }
        }
    }//GEN-LAST:event_MoveActionPerformed
       /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(myQueue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(myQueue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(myQueue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(myQueue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new myQueue().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Dequeue;
    private javax.swing.JButton Enqueue;
    private javax.swing.JButton Exit;
    private javax.swing.JButton Move;
    private javax.swing.JButton Print;
    // End of variables declaration//GEN-END:variables
}
